spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-products-service
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**
            - Method=GET
        - id: pos-carts-service
          uri: lb://pos-cart
          predicates:
            - Path=/api/cart/**
            - Method=[GET, POST, PUT, DELETE]
        - id: pos-order-service
          uri: lb://pos-order
          predicates:
            - Path=/api/order/**
            - Method=[GET, POST, PUT, DELETE]
        - id: pos-counter-service
          uri: lb://pos-counter
          predicates:
            - Path=/api/counter/**
            - Method=[POST]
#        - id: pos-delivery-service
#          uri: lb://pos-delivery
#          predicates:
#            - Path=/api/delivery/**
#            - Method=[GET, POST, PUT, DELETE]
server:
  port: 8080

micropos:
  delivery: "http://localhost:8085"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
